### ISSUE TITLE
Missing mesh files?

### ISSUE THREAD

**Issue by shadowevil** [Shturm0weak/OpenGL_Engine#2]
Trying to get the Raycast program to run and it seems to be missing a lot of mesh files... The only one included is "Tree.fbx"

Seems that even trying to render a 2d application like Raycast... The engine is still trying to run 3D models and other 3D things. Commenting out "Renderer::RenderForPostEffect()" on line 77 of Renderer.cpp fixes that issue

Minecraft runs but is missing the cubes

my recommendation is separating the 2d and 3d function calls and explicitly state in the function whether or not it's used by 2d or 3d rendering

**Comment by dajyaretakuya** [comment]
Same issue. Running raycast will trigger exception indicating `src/Mesh/Primitives` is missing.

**Comment by aleksandrturlak** [comment]
Sorry for the late reply. Yeah, the problem is in the gitignore 'cause I wrote there to ignore all fbx files. Now it has to be working, I checked it on my friend's PC and it is fine.
